version: '3.7'
services:
  frontend:
    container_name: nuxt
    image: node:14.15.1
    command: npm run dev 
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0  